# Generated by Django 3.1.5 on 2021-08-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="body",
            field=models.CharField(max_length=500, verbose_name="Body"),
        ),
        migrations.AlterField(
            model_name="article",
            name="firstParagraph",
            field=models.CharField(max_length=300, verbose_name="First Paragraph"),
        ),
        migrations.AlterField(
            model_name="article",
            name="summary",
            field=models.CharField(max_length=300, verbose_name="Summary"),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=150, verbose_name="Title"),
        ),
    ]
